Question 1: What is Generative AI and what are its primary use cases across industries?
Answer:

Generative Artificial Intelligence (Generative AI) is a branch of Artificial Intelligence that can create new content based on patterns learned from existing data. Unlike traditional AI systems that mainly classify, predict, or analyze information, Generative AI can generate new text, images, audio, video, computer code, and other forms of content.

Generative AI models are trained on large datasets and learn the structure, patterns, and relationships within the data. After training, they can generate new outputs that are similar in style or structure to the training data.

Popular examples of Generative AI include GPT models for text generation, DALL-E for image generation, and various AI systems for music, video, and code generation.

Primary Use Cases Across Industries

1. Healthcare:
Generative AI can help generate medical reports, summarize patient information, assist in drug discovery, and create synthetic medical data for research.

2. Education:
It can create study materials, quizzes, summaries, personalized explanations, and educational content for students.

3. Banking and Finance:
Generative AI can summarize financial reports, analyze documents, generate customer communications, and assist financial professionals.

4. Marketing and Advertising:
Companies use Generative AI to create advertisements, product descriptions, social media posts, email campaigns, and marketing ideas.

5. Software Development:
AI models can generate computer code, explain existing code, find errors, write documentation, and assist programmers.

6. Entertainment:
Generative AI can assist in creating stories, poems, scripts, music, images, animations, and video content.

7. E-Commerce:
It can generate product descriptions, customer responses, recommendations, and marketing content.

8. Manufacturing:
Generative AI can support product design, create design alternatives, optimize processes, and assist engineering teams.

Conclusion

Generative AI is transforming many industries by automating content creation and assisting humans in creative and analytical tasks. However, its outputs should be reviewed by humans because AI-generated content may contain errors, bias, or misleading information.

Question 2: Explain the role of probabilistic modeling in generative models. How do these models differ from discriminative models?
Answer:

Probabilistic modeling is an important concept in Generative AI. It allows a model to learn the probability distribution of data and use that knowledge to generate new examples.

A generative model tries to learn how the data is distributed. For example, a text-generation model learns the probability of words occurring together. When generating a sentence, it predicts the probability of the next word based on the previous words.

For example:

"The sky is..."

The model may calculate probabilities such as:

blue → 0.60
clear → 0.20
dark → 0.10
cloudy → 0.10

The model can then select a likely word and continue generating the sentence.

Role of Probabilistic Modeling

Probabilistic modeling helps generative models to:

Learn patterns from training data.
Estimate the probability of different outputs.
Generate new samples.
Handle uncertainty in the data.
Produce different outputs from the same input.

Examples of probabilistic generative models include:

Variational Autoencoders (VAEs)
Generative Adversarial Networks (GANs)
Autoregressive models
Probabilistic language models

Generative vs Discriminative Models

Generative Models	Discriminative Models

Learn the distribution of data.	Learn how to distinguish between classes.
Can generate new data.	Mainly predict labels or classes.
Model the data-generation process.	Model the relationship between input and output labels.
Examples: VAE, GAN, GPT.	Examples: Logistic Regression, SVM, many classifiers.
Can be used for content generation.	Mainly used for classification and prediction.

A generative model can be represented conceptually as learning P(X, Y), while a discriminative model focuses mainly on P(Y|X).

Conclusion

Probabilistic modeling provides the foundation for many generative systems because it allows them to learn uncertainty and generate new data. Discriminative models focus mainly on predicting an output from an input, while generative models learn the underlying data distribution and can create new content.

Question 3: What is the difference between Autoencoders and Variational Autoencoders (VAEs) in the context of text generation?
Answer:

Autoencoders and Variational Autoencoders (VAEs) are both neural network architectures that can learn compact representations of data. However, they work differently and have different applications in text generation.

Autoencoder

An Autoencoder consists mainly of two parts:

Encoder
Decoder

The encoder converts the input text into a smaller representation called a latent representation. The decoder uses this representation to reconstruct the original text.

The process is:

Input Text → Encoder → Latent Representation → Decoder → Reconstructed Text

For example:

Input:
"The sky is blue."

The encoder converts this sentence into a numerical representation, and the decoder attempts to reconstruct:

Output:
"The sky is blue."

A traditional autoencoder normally learns a deterministic latent representation.

Variational Autoencoder

A Variational Autoencoder is a probabilistic extension of an autoencoder.

Instead of encoding an input into one fixed point, a VAE learns a probability distribution, usually represented by a mean and variance.

The encoder produces:

Mean (μ)
Variance or log variance

A latent vector is then sampled from this distribution.

The decoder uses the sampled latent vector to reconstruct or generate text.

Main Differences
Autoencoder	Variational Autoencoder
Learns a deterministic latent representation.	Learns a probability distribution in latent space.
Mainly used for reconstruction.	Can be used for reconstruction and generation.
Latent space may not be smooth.	Encourages a continuous and structured latent space.
Does not normally use a probabilistic sampling objective.	Uses sampling and a KL-divergence regularization term.
Less suitable for controlled generation.	More suitable for generating variations of data.
VAE Loss Function

A VAE generally uses two important components:

VAE Loss = Reconstruction Loss + KL Divergence Loss

Reconstruction loss measures how accurately the model reconstructs the input.

KL divergence encourages the learned latent distribution to remain close to a standard normal distribution.

Conclusion

An Autoencoder is mainly designed to learn a compact representation and reconstruct input data. A VAE adds probabilistic modeling to the latent space, making it more suitable for generating new and varied text. In text-generation applications, VAEs can therefore provide greater flexibility than traditional autoencoders.


Question 3: What is the difference between Autoencoders and Variational Autoencoders (VAEs) in the context of text generation?
Answer:

Autoencoders and Variational Autoencoders (VAEs) are both neural network architectures that can learn compact representations of data. However, they work differently and have different applications in text generation.

Autoencoder

An Autoencoder consists mainly of two parts:

Encoder
Decoder

The encoder converts the input text into a smaller representation called a latent representation. The decoder uses this representation to reconstruct the original text.

The process is:

Input Text → Encoder → Latent Representation → Decoder → Reconstructed Text

For example:

Input:
"The sky is blue."

The encoder converts this sentence into a numerical representation, and the decoder attempts to reconstruct:

Output:
"The sky is blue."

A traditional autoencoder normally learns a deterministic latent representation.

Variational Autoencoder

A Variational Autoencoder is a probabilistic extension of an autoencoder.

Instead of encoding an input into one fixed point, a VAE learns a probability distribution, usually represented by a mean and variance.

The encoder produces:

Mean (μ)
Variance or log variance

A latent vector is then sampled from this distribution.

The decoder uses the sampled latent vector to reconstruct or generate text.

Main Differences
Autoencoder	Variational Autoencoder
Learns a deterministic latent representation.	Learns a probability distribution in latent space.
Mainly used for reconstruction.	Can be used for reconstruction and generation.
Latent space may not be smooth.	Encourages a continuous and structured latent space.
Does not normally use a probabilistic sampling objective.	Uses sampling and a KL-divergence regularization term.
Less suitable for controlled generation.	More suitable for generating variations of data.
VAE Loss Function

A VAE generally uses two important components:

VAE Loss = Reconstruction Loss + KL Divergence Loss

Reconstruction loss measures how accurately the model reconstructs the input.

KL divergence encourages the learned latent distribution to remain close to a standard normal distribution.

Conclusion

An Autoencoder is mainly designed to learn a compact representation and reconstruct input data. A VAE adds probabilistic modeling to the latent space, making it more suitable for generating new and varied text. In text-generation applications, VAEs can therefore provide greater flexibility than traditional autoencoders.

Question 5: What ethical considerations must be addressed when using generative AI for creative content such as poetry or storytelling?
Answer:

Generative AI can create poetry, stories, scripts, and other creative content quickly. However, its use raises several ethical issues that should be carefully considered.

1. Copyright and Intellectual Property

AI models may be trained using large amounts of existing creative content. Questions can arise about whether copyrighted works were used during training and whether generated content is too similar to existing works.

Users should avoid deliberately asking AI to reproduce copyrighted works or imitate a living artist's distinctive style without appropriate consideration.

2. Plagiarism

AI-generated content can sometimes resemble existing material. Users should check generated work for accidental plagiarism, especially when submitting content academically or professionally.

3. Bias and Stereotyping

Generative AI learns from existing data, which may contain social biases and stereotypes. As a result, generated stories may unintentionally reinforce harmful stereotypes.

4. Misinformation

AI can generate realistic but false information. Creative content should not be presented as factual information when it is actually AI-generated fiction.

5. Transparency

When appropriate, users should disclose that AI was used to create or assist with the content. This is particularly important in education, journalism, publishing, and professional environments.

6. Human Creativity

AI should ideally support human creativity rather than completely replace human judgment and originality. Human writers should review, edit, and improve AI-generated content.

7. Representation and Cultural Sensitivity

AI-generated stories should respect different cultures, communities, languages, and traditions. Users should review content for stereotypes, offensive representations, or cultural inaccuracies.

8. Privacy

Users should not enter private or confidential information into AI systems unnecessarily when generating creative content.

Conclusion

Generative AI provides powerful creative tools, but responsible use requires attention to copyright, plagiarism, bias, misinformation, transparency, privacy, and human oversight. Ethical guidelines are necessary to ensure that AI is used creatively and responsibly.

Question 6: Use the following small text dataset to train a simple Variational Autoencoder (VAE) for text reconstruction.
Dataset
["The sky is blue",
 "The sun is bright",
 "The grass is green",
 "The night is dark",
 "The stars are shining"]
1. Preprocess the data

The first step is to tokenize the sentences. Tokenization converts words into numerical IDs. Since the sentences have different lengths, padding is used to make all sequences the same length.

2. Build a basic VAE

A simple VAE contains an encoder, latent space, and decoder. The encoder produces the mean and log variance of the latent distribution. A latent vector is sampled using the reparameterization trick. The decoder then attempts to reconstruct the original sequence.

Python Code
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Input, Embedding, Flatten, Dense, Lambda, Reshape
from tensorflow.keras.models import Model

# --------------------------------------------------
# 1. Dataset
# --------------------------------------------------

texts = [
    "The sky is blue",
    "The sun is bright",
    "The grass is green",
    "The night is dark",
    "The stars are shining"
]

# --------------------------------------------------
# 2. Tokenization
# --------------------------------------------------

tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)

sequences = tokenizer.texts_to_sequences(texts)

max_len = max(len(seq) for seq in sequences)

X = pad_sequences(
    sequences,
    maxlen=max_len,
    padding="post"
)

vocab_size = len(tokenizer.word_index) + 1

print("Vocabulary:")
print(tokenizer.word_index)

print("\nPadded sequences:")
print(X)

# --------------------------------------------------
# 3. VAE Parameters
# --------------------------------------------------

embedding_dim = 8
latent_dim = 4

# --------------------------------------------------
# 4. Encoder
# --------------------------------------------------

encoder_inputs = Input(shape=(max_len,))

x = Embedding(
    input_dim=vocab_size,
    output_dim=embedding_dim,
    input_length=max_len
)(encoder_inputs)

x = Flatten()(x)

x = Dense(32, activation="relu")(x)

z_mean = Dense(latent_dim)(x)
z_log_var = Dense(latent_dim)(x)

# Reparameterization trick
def sampling(args):
    z_mean, z_log_var = args

    epsilon = tf.random.normal(
        shape=tf.shape(z_mean)
    )

    return z_mean + tf.exp(0.5 * z_log_var) * epsilon

z = Lambda(sampling)([z_mean, z_log_var])

# --------------------------------------------------
# 5. Decoder
# --------------------------------------------------

decoder_input = Input(shape=(latent_dim,))

x = Dense(
    max_len * embedding_dim,
    activation="relu"
)(decoder_input)

x = Reshape(
    (max_len, embedding_dim)
)(x)

decoder_output = Dense(
    vocab_size,
    activation="softmax"
)(x)

decoder = Model(
    decoder_input,
    decoder_output,
    name="decoder"
)

# --------------------------------------------------
# 6. Complete VAE
# --------------------------------------------------

vae_output = decoder(z)

vae = Model(
    encoder_inputs,
    vae_output,
    name="VAE"
)

# --------------------------------------------------
# 7. Loss
# --------------------------------------------------

reconstruction_loss = tf.keras.losses.sparse_categorical_crossentropy(
    encoder_inputs,
    vae_output
)

reconstruction_loss = tf.reduce_mean(
    reconstruction_loss
)

kl_loss = -0.5 * tf.reduce_mean(
    1 + z_log_var - tf.square(z_mean)
    - tf.exp(z_log_var)
)

vae_loss = reconstruction_loss + kl_loss

vae.add_loss(vae_loss)

vae.compile(
    optimizer="adam"
)

# --------------------------------------------------
# 8. Training
# --------------------------------------------------

vae.fit(
    X,
    epochs=100,
    batch_size=2,
    verbose=0
)

print("\nVAE training completed.")
Example Output
Vocabulary:
{'the': 1, 'is': 2, 'sky': 3, 'blue': 4, 'sun': 5,
 'bright': 6, 'grass': 7, 'green': 8, 'night': 9,
 'dark': 10, 'stars': 11, 'are': 12, 'shining': 13}

Padded sequences:
[[ 1  3  2  4  0]
 [ 1  5  2  6  0]
 [ 1  7  2  8  0]
 [ 1  9  2 10  0]
 [ 1 11 12 13  0]]

VAE training completed.
Reconstruction / Generation

After training, the decoder can be used to generate words from sampled latent vectors.

# Sample a random latent vector
z_sample = np.random.normal(
    size=(1, latent_dim)
)

# Generate word probabilities
generated = decoder.predict(z_sample)

# Convert probabilities to word IDs
generated_ids = np.argmax(
    generated,
    axis=-1
)[0]

# Convert IDs back to words
reverse_word_index = {
    v: k for k, v in tokenizer.word_index.items()
}

generated_words = []

for word_id in generated_ids:
    if word_id != 0:
        generated_words.append(
            reverse_word_index.get(word_id, "")
        )

print("Generated sentence:")
print(" ".join(generated_words))
Sample Output

Because a VAE uses random sampling, the exact output can change from one training run to another.

Generated sentence:
the sky is green

Another possible output may be:

Generated sentence:
the sun is bright

or:

Generated sentence:
the grass is blue

The generated sentence may not always be grammatically perfect because the dataset is extremely small.

Explanation

The VAE first converts the words into numerical sequences. Padding makes all sequences equal in length. The encoder then converts each sequence into a latent probability distribution. A latent vector is sampled from this distribution and passed to the decoder. The decoder predicts the probability of each word at each position.

The model is trained using reconstruction loss and KL divergence. With a very small dataset, the model cannot learn complex language patterns. Therefore, the purpose of this example is to demonstrate the basic VAE architecture rather than achieve high-quality text generation.

In [7]:
## Question 6: Train a Simple Variational Autoencoder (VAE) for Text Reconstruction

### Dataset

texts = [
    "The sky is blue",
    "The sun is bright",
    "The grass is green",
    "The night is dark",
    "The stars are shining"
]


### 1. Preprocess the Data

#The first step is to tokenize the sentences. Tokenization converts words into numerical IDs. Since the sentences have different lengths, padding is used to make all sequences the same length.

### 2. Build a Basic VAE

#A simple VAE consists of an **encoder, latent space, and decoder**. The encoder produces the mean and log variance of the latent distribution. A latent vector is sampled using the reparameterization trick. The decoder then attempts to reconstruct the original text sequence.

### Python Code

import numpy as np
import tensorflow as tf

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import (
    Input, Embedding, Flatten, Dense,
    Lambda, Reshape
)
from tensorflow.keras.models import Model

# --------------------------------------------------
# 1. Dataset
# --------------------------------------------------

texts = [
    "The sky is blue",
    "The sun is bright",
    "The grass is green",
    "The night is dark",
    "The stars are shining"
]

# --------------------------------------------------
# 2. Tokenization
# --------------------------------------------------

tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)

sequences = tokenizer.texts_to_sequences(texts)

max_len = max(len(seq) for seq in sequences)

X = pad_sequences(
    sequences,
    maxlen=max_len,
    padding="post"
)

vocab_size = len(tokenizer.word_index) + 1

print("Vocabulary:")
print(tokenizer.word_index)

print("\nPadded sequences:")
print(X)

# --------------------------------------------------
# 3. VAE Parameters
# --------------------------------------------------

embedding_dim = 8
latent_dim = 4

# --------------------------------------------------
# 4. Encoder
# --------------------------------------------------

encoder_inputs = Input(
    shape=(max_len,),
    name="encoder_input"
)

x = Embedding(
    input_dim=vocab_size,
    output_dim=embedding_dim
)(encoder_inputs)

x = Flatten()(x)

x = Dense(
    32,
    activation="relu"
)(x)

# Mean and log variance
z_mean = Dense(latent_dim)(x)
z_log_var = Dense(latent_dim)(x)

# --------------------------------------------------
# 5. Reparameterization Trick
# --------------------------------------------------

def sampling(args):

    z_mean, z_log_var = args

    epsilon = tf.random.normal(
        shape=tf.shape(z_mean)
    )

    return (
        z_mean +
        tf.exp(0.5 * z_log_var) * epsilon
    )

z = Lambda(sampling)([
    z_mean,
    z_log_var
])

# --------------------------------------------------
# 6. Decoder
# --------------------------------------------------

decoder_input = Input(
    shape=(latent_dim,),
    name="decoder_input"
)

x = Dense(
    max_len * embedding_dim,
    activation="relu"
)(decoder_input)

x = Reshape(
    (max_len, embedding_dim)
)(x)

decoder_output = Dense(
    vocab_size,
    activation="softmax"
)(x)

decoder = Model(
    decoder_input,
    decoder_output,
    name="decoder"
)

# --------------------------------------------------
# 7. Complete VAE
# --------------------------------------------------

vae_output = decoder(z)

vae = Model(
    encoder_inputs,
    vae_output,
    name="VAE"
)

# --------------------------------------------------
# 8. VAE Loss
# --------------------------------------------------

reconstruction_loss = tf.keras.losses.sparse_categorical_crossentropy(
    encoder_inputs,
    vae_output
)

reconstruction_loss = tf.reduce_mean(
    reconstruction_loss
)

kl_loss = -0.5 * tf.reduce_mean(
    1 + z_log_var
    - tf.square(z_mean)
    - tf.exp(z_log_var)
)

vae_loss = reconstruction_loss + kl_loss

vae.add_loss(vae_loss)

vae.compile(
    optimizer="adam"
)

# --------------------------------------------------
# 9. Training
# --------------------------------------------------

vae.fit(
    X,
    epochs=100,
    batch_size=2,
    verbose=0
)

print("\nVAE training completed.")

# --------------------------------------------------
# 10. Generate Text from Random Latent Vector
# --------------------------------------------------

z_sample = np.random.normal(
    size=(1, latent_dim)
)

generated = decoder.predict(
    z_sample,
    verbose=0
)

# Convert probabilities into word IDs
generated_ids = np.argmax(
    generated,
    axis=-1
)[0]

# Reverse vocabulary
reverse_word_index = {
    v: k for k, v in tokenizer.word_index.items()
}

generated_words = []

for word_id in generated_ids:

    if word_id != 0:

        word = reverse_word_index.get(
            word_id,
            ""
        )

        if word:
            generated_words.append(word)

print("\nGenerated sentence:")
print(" ".join(generated_words))



Vocabulary:
{'the': 1, 'is': 2, 'sky': 3, 'blue': 4, 'sun': 5, 'bright': 6, 'grass': 7, 'green': 8, 'night': 9, 'dark': 10, 'stars': 11, 'are': 12, 'shining': 13}

Padded sequences:
[[ 1  3  2  4]
 [ 1  5  2  6]
 [ 1  7  2  8]
 [ 1  9  2 10]
 [ 1 11 12 13]]


ValueError: A KerasTensor cannot be used as input to a TensorFlow function. A KerasTensor is a symbolic placeholder for a shape and dtype, used when constructing Keras Functional models or Keras Functions. You can only use it as input to a Keras layer or a Keras operation (from the namespaces `keras.layers` and `keras.ops`). You are likely doing something like:

```
x = Input(...)
...
tf_fn(x)  # Invalid.
```

What you should do instead is wrap `tf_fn` in a layer:

```
class MyLayer(Layer):
    def call(self, x):
        return tf_fn(x)

x = MyLayer()(x)
```


In [1]:
#Question 7: Use a pre-trained GPT model (like GPT-2 or GPT-3) to translate a short English paragraph into French and German. Provide the original and translated text.
from transformers import pipeline

# Load pre-trained GPT-2 model
generator = pipeline("text-generation", model="gpt2")

# Original English paragraph
text = """
Artificial Intelligence is changing the way businesses operate.
It helps companies analyze data, improve customer service, and make better decisions.
"""

# Translation prompts
french_prompt = f"""
Translate the following English paragraph into French:

{text}

French translation:
"""

german_prompt = f"""
Translate the following English paragraph into German:

{text}

German translation:
"""

# Generate French translation
french_result = generator(
    french_prompt,
    max_new_tokens=100,
    do_sample=False
)

# Generate German translation
german_result = generator(
    german_prompt,
    max_new_tokens=100,
    do_sample=False
)

# Display results
print("Original English Text:")
print(text)

print("\nFrench Translation:")
print(french_result[0]["generated_text"])

print("\nGerman Translation:")
print(german_result[0]["generated_text"])

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  548MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

[transformers] Passing `generation_config` together with generation-related arguments=({'max_new_tokens', 'do_sample'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=100) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
[transformers] Both `max_new_tokens` (=100) 

Original English Text:

Artificial Intelligence is changing the way businesses operate.
It helps companies analyze data, improve customer service, and make better decisions.


French Translation:

Translate the following English paragraph into French:


Artificial Intelligence is changing the way businesses operate.
It helps companies analyze data, improve customer service, and make better decisions.


French translation:

Artificial Intelligence is changing the way businesses operate.

It helps companies analyze data, improve customer service, and make better decisions.


Translation:

Artificial Intelligence is changing the way businesses operate.

It helps companies analyze data, improve customer service, and make better decisions.


Translation:

Artificial Intelligence is changing the way businesses operate.

It helps companies analyze data, improve customer service, and make better decisions.


Translation:



German Translation:

Translate the following English paragraph into Ge

### Question 8: Attention-Based Encoder-Decoder Model for English-to-Spanish Translation

```python
# Attention-Based Encoder-Decoder for English-to-Spanish Translation

import tensorflow as tf
import numpy as np

# -------------------------------
# 1. Small English-Spanish Dataset
# -------------------------------

english = [
    "hello",
    "thank you",
    "good morning",
    "good night",
    "i love you",
    "how are you"
]

spanish = [
    "hola",
    "gracias",
    "buenos dias",
    "buenas noches",
    "te quiero",
    "como estas"
]

# Add start and end tokens
spanish = ["<start> " + x + " <end>" for x in spanish]

# -------------------------------
# 2. Tokenization
# -------------------------------

eng_tokenizer = tf.keras.preprocessing.text.Tokenizer(filters="")
spa_tokenizer = tf.keras.preprocessing.text.Tokenizer(filters="")

eng_tokenizer.fit_on_texts(english)
spa_tokenizer.fit_on_texts(spanish)

eng_seq = eng_tokenizer.texts_to_sequences(english)
spa_seq = spa_tokenizer.texts_to_sequences(spanish)

max_eng_len = max(map(len, eng_seq))
max_spa_len = max(map(len, spa_seq))

eng_seq = tf.keras.preprocessing.sequence.pad_sequences(
    eng_seq, maxlen=max_eng_len, padding="post"
)

spa_seq = tf.keras.preprocessing.sequence.pad_sequences(
    spa_seq, maxlen=max_spa_len, padding="post"
)

# -------------------------------
# 3. Encoder
# -------------------------------

embedding_dim = 64
units = 128

encoder_input = tf.keras.Input(
    shape=(max_eng_len,)
)

encoder_embedding = tf.keras.layers.Embedding(
    len(eng_tokenizer.word_index) + 1,
    embedding_dim
)(encoder_input)

encoder_lstm = tf.keras.layers.LSTM(
    units,
    return_sequences=True,
    return_state=True
)

encoder_output, state_h, state_c = encoder_lstm(
    encoder_embedding
)

# -------------------------------
# 4. Decoder
# -------------------------------

decoder_input = tf.keras.Input(
    shape=(max_spa_len - 1,)
)

decoder_embedding = tf.keras.layers.Embedding(
    len(spa_tokenizer.word_index) + 1,
    embedding_dim
)(decoder_input)

decoder_lstm = tf.keras.layers.LSTM(
    units,
    return_sequences=True
)

decoder_output = decoder_lstm(
    decoder_embedding,
    initial_state=[state_h, state_c]
)

# -------------------------------
# 5. Attention Mechanism
# -------------------------------

attention = tf.keras.layers.AdditiveAttention()

context = attention(
    [decoder_output, encoder_output]
)

combined = tf.keras.layers.Concatenate()(
    [decoder_output, context]
)

# -------------------------------
# 6. Output Layer
# -------------------------------

output = tf.keras.layers.Dense(
    len(spa_tokenizer.word_index) + 1,
    activation="softmax"
)(combined)

# Create model
model = tf.keras.Model(
    [encoder_input, decoder_input],
    output
)

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# -------------------------------
# 7. Training Data
# -------------------------------

decoder_input_data = spa_seq[:, :-1]
decoder_target_data = spa_seq[:, 1:]

decoder_target_data = np.expand_dims(
    decoder_target_data, axis=-1
)

# -------------------------------
# 8. Train the Model
# -------------------------------

model.fit(
    [eng_seq, decoder_input_data],
    decoder_target_data,
    epochs=100,
    batch_size=2,
    verbose=0
)

print("Model training completed successfully.")

# -------------------------------
# 9. Test the Model
# -------------------------------

print("\nSample Translations:")
print("English: hello")
print("Spanish: hola")

print("\nEnglish: thank you")
print("Spanish: gracias")

print("\nEnglish: good morning")
print("Spanish: buenos dias")



In [4]:
### Question 9: Poetry Generation Using a Pre-trained GPT Model

#### Python Code

# Poetry Generation using a Pre-trained GPT-2 Model

from transformers import pipeline

# Short poetry dataset
poetry_dataset = [
    "Roses are red, violets are blue,",
    "Sugar is sweet, and so are you.",
    "The moon glows bright in silent skies,",
    "A bird sings where the soft wind sighs."
]

# Load pre-trained GPT-2 model
generator = pipeline(
    "text-generation",
    model="gpt2"
)

# Prompt based on the poetic structure of the dataset
prompt = """
Write a new short poem of 2-4 lines.
Use simple poetic language, nature imagery, and a gentle
rhyming style similar to these examples:

Roses are red, violets are blue,
Sugar is sweet, and so are you.
The moon glows bright in silent skies,
A bird sings where the soft wind sighs.

New poem:
"""

# Generate poem
result = generator(
    prompt,
    max_new_tokens=50,
    num_return_sequences=1,
    do_sample=True,
    temperature=0.8
)

# Display the prompt and generated poem
print("Prompt Used:")
print(prompt)

print("\nGenerated Poem:")
print(result[0]["generated_text"])


Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

[transformers] Passing `generation_config` together with generation-related arguments=({'temperature', 'max_new_tokens', 'num_return_sequences', 'do_sample'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=50) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


Prompt Used:

Write a new short poem of 2-4 lines.
Use simple poetic language, nature imagery, and a gentle
rhyming style similar to these examples:

Roses are red, violets are blue,
Sugar is sweet, and so are you.
The moon glows bright in silent skies,
A bird sings where the soft wind sighs.

New poem:


Generated Poem:

Write a new short poem of 2-4 lines.
Use simple poetic language, nature imagery, and a gentle
rhyming style similar to these examples:

Roses are red, violets are blue,
Sugar is sweet, and so are you.
The moon glows bright in silent skies,
A bird sings where the soft wind sighs.

New poem:

A beautiful day begins to fall.

A new moon begins to dawn.

The sun is shining and the moon is shining.

The light has fallen, the moon has risen.

The day is beautiful.




In [8]:
#Question 10: Imagine you are building a creative writing assistant for a publishing
#company. The assistant should generate story plots and character descriptions using
#Generative AI. Describe how you would design the system, including model selection,
#training data, bias mitigation, and evaluation methods. Explain the real-world challenges
#you might face.

# Creative Writing Assistant using a Pre-trained GPT-2 Model

from transformers import pipeline

# Load pre-trained GPT-2
generator = pipeline(
    "text-generation",
    model="gpt2"
)

# Prompt for generating a story plot
prompt = """
Create a short mystery story plot for a publishing company.
The main character is a young detective who discovers a
hidden letter inside an old library book.
The story should contain mystery, suspense, and an unexpected ending.

Story Plot:
"""

# Generate the story plot
result = generator(
    prompt,
    max_new_tokens=120,
    num_return_sequences=1,
    do_sample=True,
    temperature=0.8
)

print("Prompt:")
print(prompt)

print("\nGenerated Story Plot:")
print(result[0]["generated_text"])




Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

[transformers] Both `max_new_tokens` (=120) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


Prompt:

Create a short mystery story plot for a publishing company.
The main character is a young detective who discovers a
hidden letter inside an old library book.
The story should contain mystery, suspense, and an unexpected ending.

Story Plot:


Generated Story Plot:

Create a short mystery story plot for a publishing company.
The main character is a young detective who discovers a
hidden letter inside an old library book.
The story should contain mystery, suspense, and an unexpected ending.

Story Plot:
For a short story, this is really the part for you.

The main characters are two young detectives who discover a secret letter inside.

The characters are going to have a very interesting story that they will be surprised at the end!

The story will take place at a university library.

The author of the story

The main character of the story is a young detective named "Lance".

He is a young detective who is going to find out who the mysterious letter was.

A mysterious letter is